version: '3'

services:
  web:
    build: ./docker
    ports:
      - 8080:80
    #  - 443:443
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    env_file:
        - .env
    # user: 1000:www-data
  db:
    image: mariadb:10.6-focal
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    env_file:
      - .env
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MARIADB_HOST}
      PMA_PORT: ${MARIADB_PORT}
    ports:
      - "5001:80"
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
